### ISSUE TITLE
9.6 Compatibility

### ISSUE THREAD

**Issue by robjac** [aumhaa/m4m7#1]
Hey dude! so can't seem to get Live to pick up the midi remote scripts -- They all previously worked in 9.5.

Whilst in 9.5:
Couldn't get any of the mod m4l patchers / instruments to work with MonOhm; but did not check OhmModes. 

*notes on some specifics: I have not installed any Livid scripts. I've also dropped all ties to 9.2. 

As always, thank you.
-Robbie

**Comment by aumhaa** [comment]
Yeah, as usual, 9.6 broke everything. I’m literally working on it now.

I’ve updated the Livid scripts on GitHub, and new installers are coming.  I haven’t had time to update Mod stuff yet though…..its a HUGE undertaking, they’ve completely rewritten their framework and switched to a newer version of Python.  Might be a minute before I get it working again, but I’m definitely working on it.

Stuff should be working in 9.5 though….I’m pretty sure I checked everything a couple of weeks ago.  Unfortunately I don’t have the resources to go back and troubleshoot it right now (too many different versions!) so you may have to wait till I get things working in 9.6. 

Stay in touch, don’t be afraid of bugging me either…..I’m spinning a lot of plates right now so the reminders are helpful.

a

**Comment by robjac** [comment]
You're the best dude! -- using the Livid scripts for now. I'll be watching for commits in the next few weeks then.

**Comment by robjac** [comment]
Added the Mono Framework folder from LividRemoteScripts, and MonOhm works :+1:
