### ISSUE TITLE
CNTRL R & PUSH

### ISSUE THREAD

**Issue by RobbiSloan** [aumhaa/m4m7#2]
Hi Aumhaa

Please advice,

When using CNTRLR & PUSH in ableton, when ever using the CNTRLR , the push activates to the same channel, is there away around this happening. 

As an example, the first 4 channels, are assigned to  receive midi from CNTRLR and the next 8 channels are assigned to the PUSH, everytime i touch the CNTRLR, push dislays the channel assigned to CNTRLR.. 

I hope you understand what i mean.

**Comment by aumhaa** [comment]
I believe I do understand what you mean.  I can probably come up with a fix for your particular problem when I return home, but unfortunately I'm traveling right now and am away from my gear.  In the meantime, the best suggestion that I have is to manually lock the control surface to the device that you want it to be looking at by ctrl-clicking on the header for the device and choosing "lock to surface" option.

Feel free to bug me again in a couple weeks, just in case this issue slips through the cracks ;)

**Comment by RobbiSloan** [comment]
Thank you for you response… Il try the manual lock for now, but il mail you towards the end of the month if you don’t mind. :)

Kind Regards

Robbi Sloan
